### ISSUE TITLE
Gem is not published at rubygems.org

### ISSUE THREAD

**Issue by bombazook** [socketry/async-actor#1]
[No gem with this name at rubygems.org](https://rubygems.org/search?utf8=%E2%9C%93&query=async-actor)
Please publish it or change README

**Comment by ioquatix** [comment]
I thought this was an interesting idea - transparent RPC between Ruby processes. But the semantic complexity makes it quite tricky and can badly affect user code... I wasn't sure if it was the right design or not. So I didn't release it yet. But happy to release a v 0.1.0 it might just never go anywhere.
